project:
  type: website
  output-dir: docs

website:
  title: "Luke D. Fischer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: Research_Projects.qmd
        text: Research Projects

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

